/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_embedded_beaglebone_driver_kernel_chardev_BBNative */

#ifndef _Included_org_embedded_beaglebone_driver_kernel_chardev_BBNative
#define _Included_org_embedded_beaglebone_driver_kernel_chardev_BBNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_embedded_beaglebone_driver_kernel_chardev_BBNative
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_embedded_beaglebone_driver_kernel_chardev_BBNative_initialize
  (JNIEnv *, jclass);

/*
 * Class:     org_embedded_beaglebone_driver_kernel_chardev_BBNative
 * Method:    gpioSetValue
 * Signature: (CC)V
 */
JNIEXPORT void JNICALL Java_org_embedded_beaglebone_driver_kernel_chardev_BBNative_gpioSetValue
  (JNIEnv *, jclass, jchar, jchar);

/*
 * Class:     org_embedded_beaglebone_driver_kernel_chardev_BBNative
 * Method:    sendLcdCommand
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_org_embedded_beaglebone_driver_kernel_chardev_BBNative_sendLcdCommand
  (JNIEnv *, jclass, jchar);

/*
 * Class:     org_embedded_beaglebone_driver_kernel_chardev_BBNative
 * Method:    writeLcdLine
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_embedded_beaglebone_driver_kernel_chardev_BBNative_writeLcdLine
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_embedded_beaglebone_driver_kernel_chardev_BBNative
 * Method:    shutDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_embedded_beaglebone_driver_kernel_chardev_BBNative_shutDown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
